driver:
  mysql:
    dsn: mysql:host=127.0.0.1;dbname=kngell_eshopping;charset=utf8mb4
    dbUser: user001
    dbPass: kngell169kngell170kngell&169
  pgsql:
    dsn: mysql:host=localhost;dbname=kngellshopping;charset=utf8mb4
    dbUser: root
    dbPass: ""
