stripe:
  Publishable: pk_test_51JAMcpIZVSgv0hIY1xt5uZFEAEXC2Q1epbtWCFNl9uVQSdQZLYI3Z9Iubrkcwjd0pD7XTNnYhTkaoHnDN6buNEs900tUpx4MkP
  Secret: sk_test_51JAMcpIZVSgv0hIYSU1xRSPCZz3aUadRDEZJ8OM9qdx2QOo3oQay3Gvp3KXjE6S4Ons9YGNxZhBTsWYOlXIUCVeg00tunaxIsZ
